#ifndef GLOBAL_VARIABLES_H
#define GLOBAL_VARIABLES_H
#include <QDebug>

#define MOTOR_WARNING_ICON 0
#define BATTERY_WARNING_ICON 1
#define LOW_BATTERY_WARNING_ICON 2
#define DAY_LIGHTS_ICON 3
#define NIGHT_LIGHTS_ICON 4
#define HORN_ICON 5
#define CRUISE_CONTROL_ICON 6

// DOES NOT INCLUDE CRUISE CONTROL
// INCREASE TO 7 FOR CRUISE CONTROL
#define ICON_COUNT 6

#define SECTION_COUNT 5

#define PRESSURE_THRESHOLD 30
#define EFFICIENCY_CONSTANT 0.85f

enum states { OFF, ON };

enum gears { PARK, DRIVE, NEUTRAL, REVERSE };

enum warnings { BATTERY_FAULT, MOTOR_FAULT, LOW_BATTERY };

enum tires { FRONT_LEFT, FRONT_RIGHT, BACK_LEFT, BACK_RIGHT };

#endif // GLOBAL_VARIABLES_H
