name: Solar Car CI

on:
  push:
    branches: [ "iseanB/yamlTesting" ]
  pull_request:
    branches: [ "iseanB/yamlTesting" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: qmake
      run: qmake .
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
